[features]
seeds = false
skip-lint = false
[programs.localnet]
icoordinates_solana = "2erNMjZig8yyLCqS3xiXBQLcSYK7yVib7AcZZTA44ekm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ruiyangzhang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
